### 登录
POST http://localhost:8080/manage/admin/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"loginName":"super", "pwd":"c3284d0f94606de1fd2af172aba15bf3"}

### 登出
GET http://localhost:8080/manage/admin/logout
Accept: */*
Cache-Control: no-cache
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImp3dC1wZXJtaXNzaW9ucy1rZXlfIjoiW1wiXCIsXCJcIixcInN5czphZG1pbjpzYXZlXCIsXCJzeXM6YWRtaW46bW9kaWZ5XCIsXCJzeXM6YWRtaW46ZGVsXCIsXCJzeXM6YWRtaW46bW9kaWZ5OnJvbGVcIixcInN5czphZG1pbjpwYWdlXCIsXCJcIixcInN5czpyb2xlOnNhdmVcIixcInN5czpyb2xlOm1vZGlmeVwiLFwic3lzOnJvbGU6ZGVsXCIsXCJzeXM6cm9sZTptb2RpZnk6cGVybWlzc2lvblwiLFwic3lzOnJvbGU6cGFnZVwiLFwiXCIsXCJzeXM6cGVybWlzc2lvbjpzYXZlXCIsXCJzeXM6cGVybWlzc2lvbjptb2RpZnlcIixcInN5czpwZXJtaXNzaW9uOmRlbFwiLFwic3lzOnBlcm1pc3Npb246cGFnZVwiXSIsIm5iZiI6MTY1NTgwOTMwNCwiand0LWxvZ2luLW5hbWUiOiJzdXBlciIsImlzcyI6Imp1bmppZS5jaGVuZyIsImp3dC1yb2xlcy1rZXlfIjoiW1wi6LaF57qn566h55CG5ZGYXCJdIiwiZXhwIjoxNjU1ODE2NTA0LCJpYXQiOjE2NTU4MDkzMDR9.Jqv2g6MeyaUfbsctT7VjER5vqKu7jgkno8wzzjBR7dE

### 分页查询用户
POST http://localhost:8080/manage/admin/page
Accept: */*
Cache-Control: no-cache
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImp3dC1wZXJtaXNzaW9ucy1rZXlfIjoiW1wiXCIsXCJcIixcInN5czphZG1pbjpzYXZlXCIsXCJzeXM6YWRtaW46bW9kaWZ5XCIsXCJzeXM6YWRtaW46ZGVsXCIsXCJzeXM6YWRtaW46bW9kaWZ5OnJvbGVcIixcInN5czphZG1pbjpwYWdlXCIsXCJcIixcInN5czpyb2xlOnNhdmVcIixcInN5czpyb2xlOm1vZGlmeVwiLFwic3lzOnJvbGU6ZGVsXCIsXCJzeXM6cm9sZTptb2RpZnk6cGVybWlzc2lvblwiLFwic3lzOnJvbGU6cGFnZVwiLFwiXCIsXCJzeXM6cGVybWlzc2lvbjpzYXZlXCIsXCJzeXM6cGVybWlzc2lvbjptb2RpZnlcIixcInN5czpwZXJtaXNzaW9uOmRlbFwiLFwic3lzOnBlcm1pc3Npb246cGFnZVwiXSIsIm5iZiI6MTY1NTgwOTMwNCwiand0LWxvZ2luLW5hbWUiOiJzdXBlciIsImlzcyI6Imp1bmppZS5jaGVuZyIsImp3dC1yb2xlcy1rZXlfIjoiW1wi6LaF57qn566h55CG5ZGYXCJdIiwiZXhwIjoxNjU1ODE2NTA0LCJpYXQiOjE2NTU4MDkzMDR9.Jqv2g6MeyaUfbsctT7VjER5vqKu7jgkno8wzzjBR7dE