### 登录
POST http://localhost:8080/manage/admin/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"loginName":"super", "pwd":"c3284d0f94606de1fd2af172aba15bf3"}

### 登出
GET http://localhost:8080/manage/admin/logout
Accept: */*
Cache-Control: no-cache
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImp3dC1wZXJtaXNzaW9ucy1rZXlfIjoiW1wic3lzOmFkbWluOnNhdmVcIixcInN5czphZG1pbjptb2RpZnlcIixcInN5czphZG1pbjpkZWxcIixcInN5czphZG1pbjptb2RpZnk6cm9sZVwiLFwic3lzOmFkbWluOnBhZ2VcIixcInN5czpyb2xlOnNhdmVcIixcInN5czpyb2xlOm1vZGlmeVwiLFwic3lzOnJvbGU6ZGVsXCIsXCJzeXM6cm9sZTptb2RpZnk6cGVybWlzc2lvblwiLFwic3lzOnJvbGU6cGFnZVwiLFwic3lzOnBlcm1pc3Npb246c2F2ZVwiLFwic3lzOnBlcm1pc3Npb246bW9kaWZ5XCIsXCJzeXM6cGVybWlzc2lvbjpkZWxcIixcInN5czpwZXJtaXNzaW9uOnBhZ2VcIl0iLCJuYmYiOjE2NTU4ODIxMDIsImlzcyI6Imp1bmppZS5jaGVuZyIsImp3dC1yb2xlcy1rZXlfIjoiW1wi6LaF57qn566h55CG5ZGYXCJdIiwiZXhwIjoxNjU1ODg5MzAyLCJqd3QtbG9naW4tbmFtZV8iOiJzdXBlciIsImlhdCI6MTY1NTg4MjEwMn0.dn7ZtSh1RnM7mXTzSCOOl38Q0UUAvOZC-oR2Ntxn-3M

### 分页查询用户
POST http://localhost:8080/manage/admin/page
Accept: */*
Cache-Control: no-cache
authorization: dfdfd.xxx.yyy

### 测试
POST http://localhost:8080/manage/admin/test
Accept: */*
Cache-Control: no-cache
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImp3dC1wZXJtaXNzaW9ucy1rZXlfIjoiW1wic3lzOmFkbWluOnNhdmVcIixcInN5czphZG1pbjptb2RpZnlcIixcInN5czphZG1pbjpkZWxcIixcInN5czphZG1pbjptb2RpZnk6cm9sZVwiLFwic3lzOmFkbWluOnBhZ2VcIixcInN5czpyb2xlOnNhdmVcIixcInN5czpyb2xlOm1vZGlmeVwiLFwic3lzOnJvbGU6ZGVsXCIsXCJzeXM6cm9sZTptb2RpZnk6cGVybWlzc2lvblwiLFwic3lzOnJvbGU6cGFnZVwiLFwic3lzOnBlcm1pc3Npb246c2F2ZVwiLFwic3lzOnBlcm1pc3Npb246bW9kaWZ5XCIsXCJzeXM6cGVybWlzc2lvbjpkZWxcIixcInN5czpwZXJtaXNzaW9uOnBhZ2VcIl0iLCJuYmYiOjE2NTU4ODE5NDYsImlzcyI6Imp1bmppZS5jaGVuZyIsImp3dC1yb2xlcy1rZXlfIjoiW1wi6LaF57qn566h55CG5ZGYXCJdIiwiZXhwIjoxNjU1ODg5MTQ2LCJqd3QtbG9naW4tbmFtZV8iOiJzdXBlciIsImlhdCI6MTY1NTg4MTk0Nn0.wjA3TN1GhWbz7swP-abNO4tVmfBp1ntPQz7PfzQpjDU
