server:
  port: 30000
spring:
  application:
    name: mybatis-plus-demo

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.145.33:3306/demo?connectTimeout=1000&useUnicode=true&characterEncoding=utf-8
    username: dev
    password: dev
    # schema: classpath:db/schema-mysql.sql
    # data: classpath:db/data-mysql.sql

  # main:
    # allow-bean-definition-overriding: true