DROP TABLE IF EXISTS `demo`.`t_user`;

CREATE TABLE `demo`.`t_user`(
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '姓名',
    `age` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '年龄',
    `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表'